<?php
/**
 * Copyright 2019 Adobe
 * All Rights Reserved.
 */

/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Checkout\Block\Onepage\Success $block
 */

?>
<div class="checkout-success">
    <?php if ($block->getOrderId()): ?>
        <?php if ($block->getCanViewOrder()): ?>
            <p>
                <?= $escaper->escapeHtml(
                    __(
                        'Your order number is: %1.',
                        sprintf(
                            '<a href="%s" class="order-number"><strong>%s</strong></a>',
                            $escaper->escapeUrl($block->getViewOrderUrl()),
                            $block->getOrderId()
                        )
                    ),
                    ['a', 'strong']
                )
                ?>
            </p>
        <?php else: ?>
            <p>
                <?= $escaper->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?>
            </p>
        <?php endif; ?>
        <?php if ($block->getIsOrderStorePickup()->execute()): ?>
            <p>
                <?= $escaper->escapeHtml(__('We\'ll email you an order and pick-up confirmation with details.')) ?>
            </p>
        <?php else: ?>
            <p>
                <?= $escaper->escapeHtml(
                    __('We\'ll email you an order confirmation with details and tracking info.')
                ) ?>
            </p>
        <?php endif; ?>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $escaper->escapeUrl($block->getContinueUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
